resource_group_name     = "RG-EMEA-DDL-Sandbox"
resource_group_location = "westeurope"
storage_account_name    = "sceventsingestion"
storage_container_name  = "salescatalogupload"
service_plan_name       = "/subscriptions/f28071b5-e402-4c1a-83cc-ed0744ce8e0a/resourceGroups/RG-EMEA-DDL-Sandbox/providers/Microsoft.Web/serverFarms/ASP-RGEMEADDLSandbox-a17e"
function_app_name       = "odl-sales-catalog-ingestion" 
